import { useEffect, useMemo, useState } from 'react';
import { createAuthedSupabaseClient } from './lib/supabase';
import type { UserRole } from './api';
import './supervisor-mobile.css';

type Props={token:string;tenantId:string;role:UserRole};
type Installation={id:string;nombre:string;direccion:string|null;geocerca_radio_m:number};
type Ticket={id:string;numero_ticket:string;tipo_novedad:string;criticidad:string;estado_ticket:string;descripcion:string;instalacion_id:string;sla_limite:string|null};

export default function SupervisorMobile({token,tenantId}:Props){
 const db=useMemo(()=>createAuthedSupabaseClient(token),[token]);
 const [installations,setInstallations]=useState<Installation[]>([]),[tickets,setTickets]=useState<Ticket[]>([]);
 const [tab,setTab]=useState<'inicio'|'revistas'|'novedad'|'alertas'>('inicio');
 const [selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [form,setForm]=useState({tipo:'Seguridad',criticidad:'Media',descripcion:''});
 const load=async()=>{setBusy(true);const [i,n]=await Promise.all([db.from('supervision_instalaciones').select('id,nombre,direccion,geocerca_radio_m').order('nombre').limit(100),db.from('supervision_novedades').select('id,numero_ticket,tipo_novedad,criticidad,estado_ticket,descripcion,instalacion_id,sla_limite').neq('estado_ticket','Cerrado').order('created_at',{ascending:false}).limit(20)]);if(i.error)setMessage(i.error.message);else setInstallations(i.data||[]);if(n.error)setMessage(n.error.message);else setTickets(n.data||[]);setBusy(false)};
 useEffect(()=>{void load()},[]);
 const selectedInstallation=installations.find(i=>i.id===selected)||installations[0];
 const checkin=async(method:'GPS'|'QR'|'NFC')=>{if(!selectedInstallation)return setMessage('No tienes una instalación disponible.');setBusy(true);try{const args:{p_instalacion:string;p_metodo:string;p_lat?:number;p_lng?:number;p_codigo?:string}={p_instalacion:selectedInstallation.id,p_metodo:method};if(method==='GPS'){const pos=await new Promise<GeolocationPosition>((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:15000}));args.p_lat=pos.coords.latitude;args.p_lng=pos.coords.longitude}else{const code=prompt(method==='QR'?'Código QR:':'Identificador NFC:');if(!code)return;args.p_codigo=code.trim()}const {error}=await db.rpc('supervision_checkin',args);if(error)throw new Error(error.message);setMessage('Check-in validado correctamente.');setTab('revistas');void load()}catch(e){setMessage(e instanceof Error?e.message:'No fue posible validar el check-in.')}finally{setBusy(false)}};
 const createNovelty=async()=>{if(!selectedInstallation||!form.descripcion.trim())return setMessage('Selecciona instalación y describe la novedad.');setBusy(true);const {error}=await db.from('supervision_novedades').insert({tenant_id:tenantId,instalacion_id:selectedInstallation.id,tipo_novedad:form.tipo,criticidad:form.criticidad,descripcion:form.descripcion.trim()});setMessage(error?error.message:'Novedad registrada correctamente.');if(!error){setForm({tipo:'Seguridad',criticidad:'Media',descripcion:''});setTab('inicio');void load()}setBusy(false)};
 return <div className="supervisor-mobile"><header className="sm-header"><div><span>ALARVIX · SUPERVISOR</span><h1>{tab==='inicio'?'Centro de supervisión':tab==='revistas'?'Mis revistas':tab==='novedad'?'Nueva novedad':'Alertas'}</h1></div><button onClick={()=>void load()}>↻</button></header>{message&&<div className="sm-message">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {tab==='inicio'&&<main><section className="sm-welcome"><span>Operación de hoy</span><strong>Supervisión en campo</strong><small>{busy?'Sincronizando…':'Información actualizada'}</small></section><div className="sm-kpis"><article><b>{tickets.length}</b><span>Novedades abiertas</span></article><article><b>{tickets.filter(t=>t.criticidad==='Crítica').length}</b><span>Críticas</span></article><article><b>—</b><span>Revistas pendientes</span></article></div><section className="sm-section"><h2>Acciones rápidas</h2><div className="sm-actions"><button onClick={()=>setTab('revistas')}>📍<small>Iniciar revista</small></button><button onClick={()=>setTab('novedad')}>⚠️<small>Registrar novedad</small></button><button onClick={()=>setTab('revistas')}>🔎<small>Escanear / check-in</small></button><button onClick={()=>setTab('alertas')}>🔔<small>Ver alertas</small></button></div></section><section className="sm-section"><h2>Pendientes</h2>{tickets.slice(0,4).map(t=><article className="sm-item" key={t.id}><div><b>{t.criticidad} · #{t.numero_ticket}</b><strong>{t.tipo_novedad}</strong><small>{t.descripcion}</small></div><span>{t.estado_ticket}</span></article>)}{!tickets.length&&<p className="sm-empty">No hay novedades pendientes.</p>}</section></main>}
 {tab==='revistas'&&<main><section className="sm-section"><h2>Instalación</h2><select className="sm-select" value={selected||selectedInstallation?.id||''} onChange={e=>setSelected(e.target.value)}>{installations.map(i=><option key={i.id} value={i.id}>{i.nombre}</option>)}</select>{selectedInstallation&&<div className="sm-install"><strong>{selectedInstallation.nombre}</strong><small>{selectedInstallation.direccion||'Sin dirección'} · Geocerca {selectedInstallation.geocerca_radio_m} m</small></div>}</section><section className="sm-section"><h2>Validar presencia</h2><div className="sm-checkin"><button disabled={busy} onClick={()=>void checkin('GPS')}>📍<b>GPS</b><small>Ubicación</small></button><button disabled={busy} onClick={()=>void checkin('QR')}>▣<b>QR</b><small>Escanear</small></button><button disabled={busy} onClick={()=>void checkin('NFC')}>⌁<b>NFC</b><small>Identificar</small></button></div></section></main>}
 {tab==='novedad'&&<main><section className="sm-section"><h2>Registrar novedad</h2><label>Instalación<select className="sm-select" value={selected||selectedInstallation?.id||''} onChange={e=>setSelected(e.target.value)}>{installations.map(i=><option key={i.id} value={i.id}>{i.nombre}</option>)}</select></label><label>Tipo<select className="sm-select" value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})}><option>Seguridad</option><option>Infraestructura</option><option>Acceso</option><option>Equipo</option><option>Personal</option><option>Procedimiento</option><option>Otro</option></select></label><label>Criticidad<select className="sm-select" value={form.criticidad} onChange={e=>setForm({...form,criticidad:e.target.value})}><option>Baja</option><option>Media</option><option>Alta</option><option>Crítica</option></select></label><label>Descripción<textarea value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})} placeholder="¿Qué encontraste?"/></label><button className="sm-primary" disabled={busy} onClick={()=>void createNovelty()}>Registrar novedad</button></section></main>}
 {tab==='alertas'&&<main><section className="sm-section"><h2>Alertas</h2>{tickets.map(t=><article className="sm-alert" key={t.id}><span>{t.criticidad==='Crítica'?'🔴':t.criticidad==='Alta'?'🟠':'🟡'}</span><div><b>{t.tipo_novedad}</b><small>#{t.numero_ticket} · {t.descripcion}</small></div></article>)}{!tickets.length&&<p className="sm-empty">Sin alertas activas.</p>}</section></main>}
 <nav className="sm-bottom"><button className={tab==='inicio'?'active':''} onClick={()=>setTab('inicio')}>⌂<span>Inicio</span></button><button className={tab==='revistas'?'active':''} onClick={()=>setTab('revistas')}>✓<span>Revistas</span></button><button className={tab==='novedad'?'active':''} onClick={()=>setTab('novedad')}>+<span>Novedad</span></button><button className={tab==='alertas'?'active':''} onClick={()=>setTab('alertas')}>♢<span>Alertas</span></button></nav></div>;
}